// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Sport.App.Data;

#nullable disable

namespace Sport.App.Data.Migrations
{
    [DbContext(typeof(SportsVenuesContext))]
    partial class SportsVenuesContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseCollation("utf8mb4_0900_ai_ci")
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.HasCharSet(modelBuilder, "utf8mb4");
            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Sport.App.Data.Entities.Fixture", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<ulong>("Id"));

                    b.Property<int?>("AwayScore")
                        .HasColumnType("int")
                        .HasColumnName("away_score");

                    b.Property<string>("AwayTeamName")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("away_team_name");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("deleted_at");

                    b.Property<int?>("HomeScore")
                        .HasColumnType("int")
                        .HasColumnName("home_score");

                    b.Property<string>("HomeTeamName")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("home_team_name");

                    b.Property<string>("LeagueName")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)")
                        .HasColumnName("league_name");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("provider");

                    b.Property<string>("ProviderFixtureId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)")
                        .HasColumnName("provider_fixture_id");

                    b.Property<string>("RaceName")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("race_name");

                    b.Property<string>("SportType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("sport_type");

                    b.Property<DateTime>("StartsAt")
                        .HasColumnType("datetime")
                        .HasColumnName("starts_at");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    MySqlPropertyBuilderExtensions.UseMySqlComputedColumn(b.Property<DateTime>("UpdatedAt"));

                    b.HasKey("Id");

                    b.HasIndex("DeletedAt")
                        .HasDatabaseName("idx_fixtures_deleted_at");

                    b.HasIndex("StartsAt")
                        .HasDatabaseName("idx_fixtures_starts_at");

                    b.HasIndex("Provider", "ProviderFixtureId")
                        .IsUnique()
                        .HasDatabaseName("ux_fixture_external");

                    b.HasIndex("SportType", "LeagueName")
                        .HasDatabaseName("idx_fixtures_sport_league");

                    b.HasIndex("SportType", "StartsAt")
                        .HasDatabaseName("idx_fixtures_sport_starts");

                    b.ToTable("fixtures", (string)null);
                });

            modelBuilder.Entity("Sport.App.Data.Entities.Venue", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<ulong>("Id"));

                    b.Property<string>("Address")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("address");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Location")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("location");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("name");

                    b.Property<string>("Phone")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("phone");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    MySqlPropertyBuilderExtensions.UseMySqlComputedColumn(b.Property<DateTime>("UpdatedAt"));

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .HasDatabaseName("idx_venues_name");

                    b.ToTable("venues", (string)null);
                });

            modelBuilder.Entity("Sport.App.Data.Entities.VenueFixture", b =>
                {
                    b.Property<ulong>("VenueId")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("venue_id");

                    b.Property<ulong>("FixtureId")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("fixture_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("VenueId", "FixtureId");

                    b.HasIndex("FixtureId")
                        .HasDatabaseName("idx_vf_fixture_id");

                    b.ToTable("venue_fixtures", (string)null);
                });

            modelBuilder.Entity("Sport.App.Data.Entities.VenueFixture", b =>
                {
                    b.HasOne("Sport.App.Data.Entities.Fixture", "Fixture")
                        .WithMany("VenueFixtures")
                        .HasForeignKey("FixtureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_vf_fixture");

                    b.HasOne("Sport.App.Data.Entities.Venue", "Venue")
                        .WithMany("VenueFixtures")
                        .HasForeignKey("VenueId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_vf_venue");

                    b.Navigation("Fixture");

                    b.Navigation("Venue");
                });

            modelBuilder.Entity("Sport.App.Data.Entities.Fixture", b =>
                {
                    b.Navigation("VenueFixtures");
                });

            modelBuilder.Entity("Sport.App.Data.Entities.Venue", b =>
                {
                    b.Navigation("VenueFixtures");
                });
#pragma warning restore 612, 618
        }
    }
}
